### PR TITLE
VIN Writing Support

### PR DESCRIPTION
**Pull request by Pytrex**
Adds core logic for VIN writing support.

Usage: writevin <VIN> 
VIN is case insensitive.

### CODE REVIEW

**Comment by fenugrec** [comment]
cool that was fast. Told you it would be simple !

Proper error handling should be just aborting the command - most typical cause I expect would be losing connection (e.g. physical disconnect etc). And if it's just the ECU refusing for unknown reasons, I'd rather not force retrying; leave that decision for the user.

**Comment by Pytrex** [comment]
> cool that was fast. Told you it would be simple !

True! The template code you showed definitely helped as well!

> Proper error handling should be just aborting the command - most typical cause I expect would be losing connection (e.g. physical disconnect etc). And if it's just the ECU refusing for unknown reasons, I'd rather not force retrying; leave that decision for the user.

Right. It's not exactly a critical command that can't afford to be dropped lol

**Comment by fenugrec** [comment]
split the commit and added error handling on this branch https://github.com/fenugrec/nisprog/tree/wvin

having trouble compiling for win* due to some unrelated cppcheck errors, need to look at that closer before making a new release

**Comment by fenugrec** [comment]
Merged, thanks ! may fail to build if certain versions of cppcheck are present (problem is a too-strict setting in upstream freediag build sys), fix pending

**Pull request closed without merging**
